export type CrewType = {
  province: string
  numberClicked: string
  registraton_date: string
  namephotoA: string
  iduser: number
  autoCandidate: boolean
  selected: boolean
  rejected: boolean
  insertDate: string
  firstName: string
  lastName: string
  company: string
  address: string
  city: string
  provincia: string
  postalCode: string
  email: string
  url: string
  country: string
  passport: string
  phone: string
  mobile: string
  callWhatsapp: string
  talkApp: string
  userPhoto: string
  photoApproved: boolean
  birthYear: string
  maritalStatus: string
  smoker: string
  gender: string
  qualificationCode: string
  licenseCode: string
  seamansBook: string
  registration_Number: string
  registration_City: string
  registration_Category: string
  registration_Year: string
  courses: string
  mainPosition: string
  specseling: string
  pos_deck: string
  pos_engine: string
  pos_hotel: string
  pos_harbour: string
  pos_special: string
  ita_yachts_deck: string
  ita_yachts_engine: string
  mca_yachts_deck: string
  mca_yachts_engine: string
  mca_deck_rya: string
  stcw_navy_deck: string
  stcw_navy_engine: string
  navigationBook: string
  navigationPerformed: string
  availability: string
  dateAvailability: string
  lastAccessDate: string
  coupleWith: string
  coupleProfile: string
  salary: string
  documentStatus: string
  calculatedExperience: string
  stars: 0
  notes: string
  crewlistId: 0
  offerId: 0
  sent: boolean
  comment: string
  language1: string
  language2: string
  language3: string
  language4: string
}
