export type TCrewUser = {
  iduser: number
  published: string
  pushNotificationToken: string
  name: string
  surname: string
  yearofBirth: string
  gender: string
  maritalStatus: string
  nationality: string
  city: string
  province: string
  zip_code: string
  email: string
  emailCc: string
  cellular: string
  telephone: string
  callWhatsapp: string
  userPhoto: string
  namephotoA: string
  namephotoB: string
  namephotoC: string
  mainPosition: string
  specseling: string
  calculatedExperience: string
  availability: string
  dateAvailability: string
  lastAccessDate: string
  registrationDate: string
  seamansBook: string
  navigationBook: string
  courses: string
  qualificationCode: string
  licenseCode: string
  ita_yachts_deck: string
  ita_yachts_engine: string
  mca_yachts_deck: string
  mca_deck_rya: string
  stcw_navy_deck: string
  stcw_navy_engine: string
  pos_deck: string
  pos_engine: string
  pos_hotel: string
  pos_harbour: string
  pos_special: string
  educationalLevel: string
  language1: string
  language2: string
  language3: string
  language4: string
  relationalSkills: string
  organizationalSkills: string
  technicalSkills: string
  professionalSkills: string
  numberClick: number
  referencesNumber: number
  salary: string
  smoker: string
  couplewith: string
}
