export type ProJobOfferType = {
  idoffer: number
  iduser: number
  pushNotificationToken: string | null
  contractDescription: string
  unit: number
  gender: string
  seamensBook: string
  nauticaLicense: string
  espCharter: string
  requirements: string
  title: string
  offer: string
  offerdate: string
  offertExpirationdate: string
  descriptionOffer: string
  reference: string
  ownerDescription: string
  mainPosition: string
  jobOffer: string
  specseling: string
  posDeck: string
  posEngine: string
  posHotel: string
  posHarbour: string
  positionSpecial: string
  courses: string
  boarding: string
  duration: string
  positionArm: string
  itaYachtsDeck: string
  itaYachtsEngine: string
  mcaYachtsDeck: string
  mcaDeckRya: string
  stcwNavyDeck: string
  stcwNavyEngine: string
  salary_From: string
  salary_To: string
  latArm: number
  lngArm: number
  offerApplicable: boolean
  alreadyApplied: boolean
}

export type OwnerJobOfferType = {
  idoffer: number
  name: string
  surname: string
  username: string
  email: string
  iduser: number
  pushNotificationToken: string
  contractDescription: string
  unit: number
  gender: string
  seamensBook: string
  nauticaLicense: string
  espCharter: string
  requirements: string
  title: string
  offer: string
  offerdate: string
  offertExpirationdate: string
  descriptionOffer: string
  reference: string
  countCandidates: number
  countContacted: number
  countResidual: number
  ownerDescription: string
  mainPosition: string
  jobOffer: string
  specseling: string
  posDeck: string
  posEngine: string
  posHotel: string
  posHarbour: string
  positionSpecial: string
  courses: string
  boarding: string
  duration: string
  positionArm: string
  itaYachtsDeck: string
  itaYachtsEngine: string
  mcaYachtsDeck: string
  mcaDeckRya: string
  stcwNavyDeck: string
  stcwNavyEngine: string
  salary_From: string
  salary_To: string
  latArm: number
  lngArm: number
  listurl: string
  listgeourl: string
  offerApplicable: boolean
  alreadyApplied: boolean
}
