export type User = {
  name: string
  surname: string
  company: string
  address: string
  city: string
  province: string
  emailCc: string
  email: string
  url: string
  telephone: string
  telephone1: string
  phoneprefix: string
  landprefix: string
  whatsAppprefix: string
  cellular: string
  fax: string
  skype: string
  last_access_date: string
  pushNotificationToken: string
  iduser: number
  userTypeIta: string
  zip_code: string
  suspended: string
  passportCode: string
  consentMarketing: string
  userPhoto: string
  photoapproved: string
  talkApp: string
  lat: string
  lng: string
  positionbase: string
  positionDescription: string
  qlfn: string
  yearofBirth: string
  gender: true
  nationality: string
  language1: string
  serialnumberCity: string
  serialnumber: string
  serialnumberGdm: true
  serialnumberCategory: string
  serialnumberSkill: string
  serialnumberLicence: string
  serialnumberData: string
  navigationBooklet: number
  navigationCompleted: number
  courses: string
  notesCourses: string
  boardingpreference: string
  availability: true
  availabilityperiod: string
  assignment: string
  smoker: number
  team: true
  couplewith: string
  card1Couple: string
  salary: string
  registrationdate: string
  lastaccessdate: number
  curriculum: string
  coupleOther: string
  civilstate: true
  experience: string
  language2: string
  language3: string
  language4: string
  experienceEmbarkations: string
  preference: string
  duration: string
  availablefor: string
  numberClick: number
  specVela: number
  vaxCovid19: true
  lastvaxcovid19date: string
  coursesCode: string
  position: string
  posDeck: string
  posEngine: string
  posHotel: string
  posHarbour: string
  posSpecial: string
  itaYachtsDeck: string
  itaYachtsEngine: string
  mcaYachtsDeck: string
  mcaYachtsEngine: string
  mcaDeckRya: string
  stcwNavyDeck: string
  stcwNavyEngine: string
  registrationnumberqualificationcode: string
  dateavailabilityfrom: number
  registrationnumberlicensecode: string
  passport: string
  secondaryTasks: string
  matricola_citta: string
  matricola: string
  matricola_GDM: string
  matricola_categoria: string
  matricola_patentecode: string
  namephotoA: string
  namephotoB: string
  namephotoC: string
  idUtente: number
  zipcode: string
  registration_date: string
}
