export type TUser = {
  iduser: number
  published: string // API field: "publisched" (server-side typo), mapped in profile.ts
  suspended: string
  reported: string
  incomplete: string
  pushNotificationToken: string
  userName: string
  name: string
  surname: string
  yearofBirth: string
  gender: string
  maritalStatus: string
  nationality: string
  company: string
  address: string
  city: string
  province: string
  zip_code: string
  emailCc: string
  email: string
  url: string
  telephone: string
  cellular: string
  callWhatsapp: string
  userPhoto: string
  smoker: string
  lat: string
  lng: string
  mainPosition: string
  qualificationCode: string
  licenseCode: string
  seamansBook: string
  registration_Number: string
  registration_City: string
  registration_Category: string
  registration_Year: string
  navigationBook: string
  calculatedExperience: string
  availability: string
  dateAvailability: string
  lastAccessDate: string
  registrationDate: string
  courses: string
  notesCourses: string
  specseling: string
  couplewith: string
  card1Couple: string
  salary: string
  educationalLevel: string
  language1: string
  language2: string
  language3: string
  language4: string
  pos_deck: string
  pos_engine: string
  pos_hotel: string
  pos_harbour: string
  pos_special: string
  ita_yachts_deck: string
  ita_yachts_engine: string
  mca_yachts_deck: string
  mca_deck_rya: string
  stcw_navy_deck: string
  stcw_navy_engine: string
  numberClick: number
  passport: string
  secondaryTasks: string
  namephotoA: string
  namephotoB: string
  namephotoC: string
}
